### ISSUE TITLE
Delphi packages

### ISSUE THREAD

**Issue by mdbs99** [mdbs99/xavier#2]
Let's build packages (lib and test) for Delphi.
We need to code the same implementation using `xavier.core.fpc.pas` unit. The unit for Delphi should be named `xavier.core.delphi.pas`.

**Comment by mdbs99** [comment]
@nunopicado please take a look on these files. I created them manually, then can have some errors.

**Comment by nunopicado** [comment]
It was close to perfect. :)
I'll send you a PR with some minor changes I had to do, along with the test project for Delphi.

**Comment by mdbs99** [comment]
Thank you.
