### ISSUE TITLE
XPath method should be renamed?

### ISSUE THREAD

**Issue by mdbs99** [mdbs99/xavier#6]
The `IXMLPack` interface has a method `XPath` that returns a `IXMLNode` (a single node).
I don't know if this is the better approach.
If `XPath` doesn't return a valid instance, means that we'll get `nil`, ie, access violation error.

A safe option is returns a `IXMLNodes` list. But this makes the design a little bit ugly when we want to work with only a node.

See this example below.
Let's suppose that we want to know the node `value`:
```pascal
   TXMLPack.New(TFile.New('file.xml').Stream).XPath(
      '/CONFIG/Package/Name'
    )
    .Item(0)  // << We'll need this, if we return a list 
    .Value
``` 

However, this design/syntax already exists.

In the example below, if we want to know the `value` of the first attribute of the first node found, we need to code like that:

```pascal
   TXMLPack.New(TFile.New('file.xml').Stream).XPath(
      '/CONFIG/Package/Name'
    )
    .Item(0)  // << new, as explaned above
    .Attrs
    .Item(0)
    .Value
``` 

Another option is having two methods which returns a single node or a node list:
```pascal
function XPath(const AExpr: XMLString): IXMLNode;
function XPaths(const AExpr: XMLString): IXMLNodes;
``` 

Or could be:
```pascal
function Node(const AExpr: XMLString): IXMLNode;
function Nodes(const AExpr: XMLString): IXMLNodes;
``` 

For the method that returns a single node, the library must raise an exception if couldn't find anything.
For the method that returns a list, it will be just a empty list, but without any problems with `nil`.

**Comment by mdbs99** [comment]
@nunopicado what do you think?

**Comment by nunopicado** [comment]
I think this is the best approach:

```delphi
function Node(const AExpr: XMLString): IXMLNode;
function Nodes(const AExpr: XMLString): IXMLNodes;
```

I don't dislike the idea of using a single method returning a list, since it is common place for XML consumers (XML is a list of nodes, after all).
But having both is useful too.

**Comment by mdbs99** [comment]
I agree with you. I like the last option too, and you just confirmed that is the best approach.
I'll fix that. Thanks.
