### ISSUE TITLE
XPath for Delphi

### ISSUE THREAD

**Issue by mdbs99** [mdbs99/xavier#8]
Let's implements XPath for Delphi (`TXMLPack.Nodes method`).

**Comment by mdbs99** [comment]
@nunopicado could you handle this?
This [article](http://www.zettaomnis.net.br/portal/a2d-mei/articles-a2d-mei/132-manipulando-xmls-com-xpath.html) could help you, if you do not know XPath.

**Comment by nunopicado** [comment]
Yes, I can, but only next week, as I have the weekend booked.

**Comment by mdbs99** [comment]
@nunopicado Ok.
Maybe some test won't work when compile on Delphi or even won't possible to compile.
Please, take a look, if possible.
Thank you.

**Comment by mdbs99** [comment]
@nunopicado do you have any news about this issue?

**Comment by mdbs99** [comment]
@nunopicado, hello.
I'm back. The code was almost completely rewrite - at least the structure and units to make it more (old) Delphi compatible.
Would like to continue on this task?

**Comment by nunopicado** [comment]
I've got my time table mess up for a several months now, like you probably noticed by my absence.
I cannot get to it for the time being. I'm not really sure when I will be able to get back to it. :/

**Comment by mdbs99** [comment]
Hey @nunopicado no problem. I will develop it by my own, but I would like to see you here as soon as possible. Take care!

**Comment by nunopicado** [comment]
I'll try... :)

**Comment by mdbs99** [comment]
Done - see all commits on Apr 10, 2019.
